source 'https://github.com/CocoaPods/Specs.git'

target 'LSDImagesCache', :exclusive => true do
  pod "LSDImagesCache", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LSDImagesCache", :path => "../"

  
end
